version: "3.8"

services:
  gath:
    container_name: gath
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=Gatherings"
    volumes:
      - ./src:/var/www
    depends_on:
      - db
      - redis

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./build/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ..:/var/www:rw
    depends_on:
      - gath

  db:
    image: mysql:8.0
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gatherings
      MYSQL_USER: gath
      MYSQL_PASSWORD: gath

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6385:6379"

volumes:
  db_data:
