version: "3.8"

services:
  gath:
    container_name: gath
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=Gatherings"
    volumes:
      - ./src:/var/www
    depends_on:
      - postgres
      - redis

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./build/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ..:/var/www:rw
    depends_on:
      - gath

  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6385:6379"

volumes:
  db_data:
